version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: null
      MYSQL_PASSWORD: null
      MYSQL_DATABASE: mevn_challenge
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5
  server:
    build: server
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
  webapp:
    build: webapp
    ports:
      - 8080:80
    depends_on:
      - server
volumes:
  db_data: {}